### PR TITLE
Update 2017.2

### PR DESCRIPTION
**Pull request by joedborg**

### CODE REVIEW

**Comment by evandandrea** [comment]
Looks good!

**Comment by joedborg** [comment]
Hey Evan,

It doesn't seem to have deployed the snap to the store.

Thanks,
Joe

**Comment by evandandrea** [comment]
It's r24:
https://build.snapcraft.io/user/snapcrafters/pycharm-professional/60452

You should get it if you `snap refresh --edge pycharm-professional`. Or are
you asking me to promote that rev to stable?

**Comment by joedborg** [comment]
Yep, please put it to stable. 

Thanks!

**Comment by evandandrea** [comment]
I've released r24 to stable and closed candidate and beta so they track stable.

```
$ snapcraft release pycharm-professional 24 stable
Track    Arch    Channel    Version    Revision
latest   amd64   stable     2017.2     24
                 candidate  2017.1.5   14
                 beta       2017.1.5   14
                 edge       2017.2     24
$ snapcraft close pycharm-professional candidate
Track    Arch    Channel    Version    Revision
latest   amd64   stable     2017.2     24
                 candidate  ^          ^
                 beta       2017.1.5   14
                 edge       2017.2     24
         armhf   stable     2017.1.2   4
                 candidate  ^          ^
                 beta       2017.1.2   4
                 edge       2017.1.2   4

The candidate channel is now closed.
$ snapcraft close pycharm-professional beta
Track    Arch    Channel    Version    Revision
latest   amd64   stable     2017.2     24
                 candidate  ^          ^
                 beta       ^          ^
                 edge       2017.2     24
         armhf   stable     2017.1.2   4
                 candidate  ^          ^
                 beta       ^          ^
                 edge       2017.1.2   4

The beta channel is now closed.
```
I've also filed [1706786](https://bugs.launchpad.net/snapstore/+bug/1706786) for the armhf build failing to release.

Do let me (or @popey) know if there are revisions for any other snaps you'd like promoted to stable. Thanks for updating and testing this!

**Pull request merged**
